### ISSUE TITLE
non-OK status from mijn.host API 400

### ISSUE THREAD

**Issue by FutureCow** [mijnhost/certbot-dns-mijn-host#3]
Nice to see a certbot-DNS for mijn.host. Tried it today, but got this error: non-OK status from mijn.host API 400

log:
```
Creating MijnHostClient
Starting new HTTPS connection (1): mijn.host:443
https://mijn.host:443 "GET /api/v2/domains/domain.nl/dns HTTP/11" 200 1177
Starting new HTTPS connection (1): mijn.host:443
https://mijn.host:443 "PUT /api/v2/domains/domain.nl/dns HTTP/11" 400 125
Encountered exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/certbot/_internal/auth_handler.py", line 88, in handle_authorizations
    resps = self.auth.perform(achalls)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot/plugins/dns_common.py", line 76, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/local/lib/python3.11/dist-packages/certbot_dns_mijn_host/mijn_host.py", line 47, in _perform
    self._get_mijn_host_client().add_txt_record(
  File "/usr/local/lib/python3.11/dist-packages/certbot_dns_mijn_host/mijn_host.py", line 106, in add_txt_record
    self.update_records(domain, records)
  File "/usr/local/lib/python3.11/dist-packages/certbot_dns_mijn_host/mijn_host.py", line 88, in update_records
    resp = self._handle_response(req, name="update records")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot_dns_mijn_host/mijn_host.py", line 69, in _handle_response
    raise errors.PluginError(
certbot.errors.PluginError: Received non-OK status from mijn.host API 400

Calling registered functions
Cleaning up challenges
Creating MijnHostClient
Starting new HTTPS connection (1): mijn.host:443
https://mijn.host:443 "GET /api/v2/domains/domain.nl/dns HTTP/11" 200 1177
Starting new HTTPS connection (1): mijn.host:443
https://mijn.host:443 "PUT /api/v2/domains/domain.nl/dns HTTP/11" 200 76
Creating MijnHostClient
Starting new HTTPS connection (1): mijn.host:443
https://mijn.host:443 "GET /api/v2/domains/domain.nl/dns HTTP/11" 200 1177
Starting new HTTPS connection (1): mijn.host:443
https://mijn.host:443 "PUT /api/v2/domains/domain.nl/dns HTTP/11" 200 76
Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot/_internal/main.py", line 1894, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot/_internal/main.py", line 1600, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot/_internal/main.py", line 143, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot/_internal/client.py", line 517, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot/_internal/auth_handler.py", line 88, in handle_authorizations
    resps = self.auth.perform(achalls)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot/plugins/dns_common.py", line 76, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/local/lib/python3.11/dist-packages/certbot_dns_mijn_host/mijn_host.py", line 47, in _perform
    self._get_mijn_host_client().add_txt_record(
  File "/usr/local/lib/python3.11/dist-packages/certbot_dns_mijn_host/mijn_host.py", line 106, in add_txt_record
    self.update_records(domain, records)
  File "/usr/local/lib/python3.11/dist-packages/certbot_dns_mijn_host/mijn_host.py", line 88, in update_records
    resp = self._handle_response(req, name="update records")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot_dns_mijn_host/mijn_host.py", line 69, in _handle_response
    raise errors.PluginError(
certbot.errors.PluginError: Received non-OK status from mijn.host API 400
Received non-OK status from mijn.host API 400
```

**Comment by shubhamku044** [comment]
I will check this, thanks for reporting

**Comment by daxy01** [comment]
I've got the API 400 code as well.
It might be because of sub-domains as this works:
`certbot certonly -n --authenticator dns-mijn-host --dns-mijn-host-credentials /etc/letsencrypt/credentials.ini --dns-mijn-host-propagation-seconds 60 --agree-tos -d 'domain.nl' -d '*.home.domain.nl' -v`

While this one does not work:
`certbot certonly -n --authenticator dns-mijn-host --dns-mijn-host-credentials /etc/letsencrypt/credentials.ini --dns-mijn-host-propagation-seconds 60 --agree-tos -d 'domain.nl' -d '*.home.domain.nl' -v`

**Comment by mvdnes** [comment]
I am having the same issue when trying to obtain a certificate for 'server.lan.domain.nl'. I see the following in the logs:

```
https://mijn.host:443 "GET /api/v2/domains/server.lan.domain.nl/dns HTTP/11" 400 88
```

It appears not to strip the subdomain from the API url.

**Comment by mvdnes** [comment]
I do not know if this actually is the same error as @FutureCow ran into, but I have created a pull request #5 to allow for sub-domains.

**Comment by mijnhost** [comment]
Thank you @mvdnes. We've tested your PR and it looks like this fixed it. It's now merged.
Please let us know if you still encounter issues.
